version: "2.1"
services:
  db:
    # Oracle-packaged version includes a `linux/arm64/v8` version, needed for
    # machines with Apple Silicon CPUs (Mac M1, M2)
    image: mysql:8.0.33-oracle
    container_name: edx_exams.db
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - devstack_default
    volumes:
      - edx_exams_mysql:/var/lib/mysql

  memcache:
    image: memcached:1.4.24
    container_name: edx_exams.memcache

  app:
    # Uncomment this line to use the official edx_exams base image
    image: edxops/edx_exams

    container_name: edx_exams.app
    volumes:
      - .:/edx/app/edx-exams/
    command: bash -c 'while true; do python /edx/app/edx-exams/manage.py runserver 0.0.0.0:18740; sleep 2; done'
    environment:
      DJANGO_SETTINGS_MODULE: edx_exams.settings.devstack
    ports:
      - "18740:18740"
    networks:
      - devstack_default
    stdin_open: true
    tty: true

networks:
  devstack_default:
    external: true

volumes:
  edx_exams_mysql:
