name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches:
    - '**'


jobs:
  run_tests:
    name: tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        python-version: ['3.8']
        toxenv: [django32, django40, quality, pii_check]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: "0"

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pip
      run: pip install -r requirements/pip.txt

    - name: Install Dependencies
      run: pip install -r requirements/ci.txt

    - name: Run Tests
      env:
        TOXENV: ${{ matrix.toxenv }}
      run: tox

    - name: Report coverage
      if: matrix.python-version == '3.8' && matrix.toxenv == 'django32'
      uses: thollander/actions-comment-pull-request@v2
      with:
        filePath: diff-cover.md
        comment_tag: diff-cover
